// apps/docs/app/components/CardCover.vue
<script setup lang="ts">
const props = defineProps<{ src: string }>()

const isLoading = ref(true)
const cover = shallowRef<HTMLImageElement>()

function onLoad() {
  isLoading.value = false
}

onMounted(() => {
  if (cover.value?.complete) {
    isLoading.value = false
  }
})
</script>

<template>
  <picture class="relative overflow-hidden">
    <div v-if="isLoading" class="p-8 bg-black inset-0 absolute z-10">
      <img alt="loading" class="size-full object-contain" src="/loading.webp" />
    </div>
    <img
      ref="cover"
      alt="cover"
      class="card-cover"
      loading="lazy"
      :src="props.src"
      @load="onLoad"
    />
  </picture>
</template>

// apps/docs-next/src/app/docs/archive/CardCover.tsx
'use client'
import { useEffect, useRef, useState } from 'react'

export function CardCover({ src }: { src: string }) {
  const [isLoading, setLoading] = useState(true)
  const cover = useRef<HTMLImageElement>(null!)

  function onLoad() {
    setLoading(false)
  }

  useEffect(() => {
    if (cover.current?.complete) {
      setLoading(false)
    }
  }, [])

  return (
    <picture className="relative overflow-hidden">
      {isLoading && (
        <div className="p-8 bg-black inset-0 absolute z-10">
          <img
            alt="loading"
            className="size-full object-contain"
            src="/loading.webp"
          />
        </div>
      )}
      <img
        alt="cover"
        className="card-cover"
        loading="lazy"
        onLoad={onLoad}
        ref={cover}
        src={src}
      />
    </picture>
  )
}
