// apps/docs-next/src/theme/components/popover/Popover.tsx
import type { PropsWithChildren, RefObject } from 'react'
import type { Timer, WithHTMLProps } from '../../types'
import type { PopoverProps } from './index'
import { clsx } from '@repo/utils'
import {
  cloneElement,
  createContext,
  isValidElement,
  useContext,
  useEffect,
  useEffectEvent,
  useRef
} from 'react'
import { createPortal } from 'react-dom'
import { stylex } from '#/utils'
import { useEventListener } from '../../hooks'
import { usePopoverState } from './state'

function Popover(props: PropsWithChildren<PopoverProps>) {
  const {
    isOpen,
    onOpenChange,
    trigger = 'click',
    placement = 'bottom',
    maskClosable = true,
    keepAlive = false,
    fixed = false,
    offset = 10,
    delayClose = 200,
    children,
    onOpen,
    onClose
  } = props

  const { tRef, vRef, visible, isActive, translate, open, close } =
    usePopoverState({ placement, keepAlive, fixed, offset, onOpen, onClose })

  console.log('render')

  useEffect(() => {
    if (isOpen) {
      handleOpen()
    } else {
      handleClose()
    }
  }, [isOpen])

  const handleOpen = () => {
    if (visible) return
    open()
    onOpenChange?.(true)
  }

  const handleClose = () => {
    if (!visible) return
    close()
    onOpenChange?.(false)
  }

  const timer = useRef<Timer | null>(null)

  const { addEventListener } = useEventListener()

  const onClickOutside = useEffectEvent((event: PointerEvent) => {
    console.log('onClickOutside')
    if (!visible) return
    const elements = event.composedPath()
    const tDOM = tRef.current
    const vDOM = vRef.current
    for (const ele of elements) {
      if (ele === tDOM || ele === vDOM) {
        return
      }
    }
    handleClose()
  })

  useEffect(() => {
    if (maskClosable && trigger === 'click') {
      addEventListener(window, 'click', onClickOutside)
    }
  }, [])

  const ctxValue: PopoverContext = {
    tRef,
    vRef,
    timer,
    trigger,
    fixed,
    delayClose,
    visible,
    isActive,
    translate,
    handleOpen,
    handleClose
  }

  return <PopoverContext value={ctxValue}>{children}</PopoverContext>
}

interface PopoverContext {
  tRef: RefObject<Element | null>
  vRef: RefObject<Element | null>
  timer: RefObject<Timer | null>
  trigger?: 'hover' | 'click'
  fixed: boolean
  delayClose: number
  visible: boolean
  isActive: boolean
  translate: { x: number; y: number }
  handleOpen: () => void
  handleClose: () => void
}

const PopoverContext = createContext({} as PopoverContext)

function PopoverTrigger({ children }: PropsWithChildren) {
  const { tRef, timer, trigger, delayClose, visible, handleOpen, handleClose } =
    useContext(PopoverContext)

  if (!isValidElement(children) || Array.isArray(children)) {
    return null
  }

  const onClick = () => {
    visible ? handleClose() : handleOpen()
  }

  const onPointerEnter = () => {
    timer.current && window.clearTimeout(timer.current)
    handleOpen()
  }

  const onPointerLeave = () => {
    timer.current = setTimeout(handleClose, delayClose)
  }

  const events =
    trigger === 'click' ? { onClick } : { onPointerEnter, onPointerLeave }

  return cloneElement<any>(children, { ref: tRef, ...events })
}

interface PopoverContentProps extends WithHTMLProps {}

function PopoverContent(props: PropsWithChildren<PopoverContentProps>) {
  const { className, style, children, ...restProps } = props
  const {
    vRef,
    timer,
    trigger,
    fixed,
    visible,
    isActive,
    translate,
    handleClose
  } = useContext(PopoverContext)

  if (!isActive) return null

  const wrapperStyle = stylex(
    {
      '--x': `${translate.x}px`,
      '--y': `${translate.y}px`,
      display: !visible && 'none',
      position: fixed ? 'fixed' : 'absolute',
      translate: 'var(--x) var(--y)'
    },
    style
  )

  function onPointerEnter() {
    timer.current && window.clearTimeout(timer.current)
  }

  function onPointerLeave() {
    trigger === 'hover' && handleClose()
  }

  const content = (
    <div
      className={clsx(
        'pointer-events-none top-0 left-0 z-1000 contain-layout',
        className
      )}
      onPointerEnter={onPointerEnter}
      onPointerLeave={onPointerLeave}
      ref={vRef as any}
      style={wrapperStyle}
      {...restProps}
    >
      {children}
    </div>
  )

  return createPortal(content, document.body)
}

Popover.Trigger = PopoverTrigger
Popover.Content = PopoverContent

export { Popover }

// packages/theme/src/components/popover/Popover.vue
<script setup lang='ts'>
import type { ComponentPublicInstance } from 'vue'
import type { Timer } from '#/types'
import type { PopoverProps } from '.'
import { useEventListener } from '@repo/utils/hooks'
import { computed, h, onMounted, watch } from 'vue'
import TeleportToBody from '#/components/TeleportToBody.vue'
import { usePopoverState } from './state.ts'

const props = withDefaults(defineProps<PopoverProps>(), {
  trigger: 'click',
  placement: 'bottom',
  maskClosable: true,
  keepAlive: false,
  fixed: false,
  width: 150,
  offset: 10,
  closeDelay: 200,
  onClose: () => {}
})

const slots = defineSlots<{
  default(): any[]
  trigger(): any[]
}>()

const { isActive, show, visible, tRef, vRef, translate, open, close } =
  usePopoverState(props)

const model = defineModel<boolean>('open')

const handleOpen = () => {
  model.value = true
  open()
}

const handleClose = () => {
  model.value = false
  close()
}

watch(
  () => model.value,
  open => {
    if (open) {
      handleOpen()
    } else {
      handleClose()
    }
  }
)

let timer: Timer | null = null
const clearTimer = () => timer && clearTimeout(timer)

function createEvents(): {
  onClick?: () => void
  onPointerenter?: () => void
  onPointerleave?: () => void
} {
  const onClick = () => {
    show.value ? handleClose() : handleOpen()
  }

  const onMouseEnter = () => {
    clearTimer()
    handleOpen()
  }

  const onMouseLeave = () => {
    timer = setTimeout(handleClose, props.closeDelay)
  }

  if (props.trigger === 'click') {
    return { onClick }
  }
  return {
    onPointerenter: onMouseEnter,
    onPointerleave: onMouseLeave
  }
}

const events = createEvents()

const TriggerElement = () => {
  const elements = slots.trigger()
  if (elements.length !== 1) {
    return null
  }

  return h(elements[0], {
    ref: value => (tRef.value = value),
    ...events
  })
}

const triggerDOM = computed(() => {
  const value = tRef.value
  return (value as ComponentPublicInstance)?.$el ?? value
})

function onClickOutside(event: PointerEvent) {
  const elements = event.composedPath()
  const tDOM = triggerDOM.value
  const vDOM = vRef.value
  for (const ele of elements) {
    if (ele === tDOM || ele === vDOM) {
      return
    }
  }
  handleClose()
}

const { addEventListener } = useEventListener()
onMounted(() => {
  if (props.maskClosable) {
    addEventListener(window, 'pointerdown', onClickOutside)
  }
})
</script>

<template>
  <TriggerElement />
  <TeleportToBody id="popover">
    <div
      v-if="isActive"
      v-show="show"
      ref="vRef"
      class="popover"
      :style="{
        '--x': `${translate.x}px`,
        '--y': `${translate.y}px`,
        position: fixed ? 'fixed' : 'absolute',
        opacity: visible ? undefined : 0
      }"
      @pointerenter="clearTimer"
      @pointerleave="events.onPointerleave"
    >
      <slot></slot>
    </div>
  </TeleportToBody>
</template>

<style>
.popover {
  contain: layout;
  top: 0;
  left: 0;
  transform-origin: center;
  pointer-events: auto;
  translate: var(--x) var(--y);
  z-index: 1000;
}
</style>
