// packages/theme/src/prose/AnchorHead.vue
<script setup lang='ts'>
import { Hash } from '#/icons'

const props = defineProps<{
  tag: string
  id?: string
}>()
</script>

<template>
  <component :is="tag" :id="id" v-bind="$attrs">
    <a class="group inline-flex items-center relative" :href="`#${id}`">
      <span
        :class="[
          'rounded-md flex size-5 flex-center cursor-pointer absolute',
          'text-muted-foreground bg-muted hover:text-brand duration-250',
          'opacity-0 group-hover:opacity-100 transition-opacity'
        ]"
      >
        <Hash class="size-4" />
      </span>
      <span class="transition-transform duration-250 group-hover:translate-x-6">
        <slot></slot>
      </span>
    </a>
  </component>
</template>

// apps/docs-next/src/theme/prose/AnchorHead.tsx
'use client'
import type { PropsWithChildren } from 'react'
import type { WithHTMLProps } from '../types'
import { clsx } from '@repo/utils'
import { createElement } from 'react'
import { Hash } from '../icons'

interface Props extends WithHTMLProps<HTMLHeadingElement> {
  tag: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'
  id?: string
}

export function AnchorHead(props: PropsWithChildren<Props>) {
  const { tag, id, children, ...attrs } = props
  return createElement(
    tag,
    { id, ...attrs },
    <Anchor id={id}>{children}</Anchor>
  )
}

function Anchor(props: PropsWithChildren<{ id?: string }>) {
  const { id = '', children } = props

  return (
    <a className="group inline-flex items-center relative" href={`#${id}`}>
      <span
        className={clsx(
          'rounded-md flex size-5 cursor-pointer flex-center absolute',
          'text-muted-foreground bg-muted duration-250 hover:text-brand',
          'opacity-0 transition-opacity group-hover:opacity-100'
        )}
      >
        <Hash />
      </span>
      <span className="transition-transform duration-250 group-hover:translate-x-6">
        {children}
      </span>
    </a>
  )
}
