// packages/theme/src/prose/CustomBlock.tsx
import type { SetupContext } from 'vue'

interface Props {
  type?: 'info' | 'warning' | 'danger'
  title?: string
}

export function CustomBlock(props: Props, { slots }: SetupContext) {
  const { type = 'info' } = props
  const title = props.title ?? type.toUpperCase()

  return (
    <div class="custom-block" data-type={type}>
      <p class="font-600">{title}</p>
      {slots.default?.()}
    </div>
  )
}

// apps/docs-next/src/theme/prose/CustomBlock.tsx
'use client'
import type { PropsWithChildren } from 'react'

interface Props {
  type?: 'info' | 'warning' | 'danger'
  title?: string
}

export function CustomBlock(props: PropsWithChildren<Props>) {
  const { type = 'info', children } = props
  const title = props.title ?? type.toUpperCase()

  return (
    <div className="custom-block" data-type={type}>
      <p className="font-600">{title}</p>
      {children}
    </div>
  )
}
