// packages/theme/src/prose/CustomBlock.vue
<script setup lang='ts'>
import { computed } from 'vue'

interface Props {
  type?: 'info' | 'warning' | 'danger'
  title?: string
}

const props = withDefaults(defineProps<Props>(), { type: 'info' })

const title = computed(() => props.title ?? props.type.toUpperCase())
</script>

<template>
  <div class="custom-block" :data-type="type">
    <p class="font-600">{{ title }}</p>
    <slot></slot>
  </div>
</template>

// apps/docs-next/src/theme/prose/CustomBlock.tsx
'use client'
import type { PropsWithChildren } from 'react'

interface Props {
  type?: 'info' | 'warning' | 'danger'
  title?: string
}

export function CustomBlock(props: PropsWithChildren<Props>) {
  const { type = 'info', children } = props
  const title = props.title ?? type.toUpperCase()

  return (
    <div className="custom-block" data-type={type}>
      <p className="font-600">{title}</p>
      {children}
    </div>
  )
}
