// apps/docs/app/components/content/ProsePre.vue
<script setup lang="ts">
import { Copy, CopyCheck } from 'ebb-theme/icons'

// reference: https://github.com/nuxt-content/mdc/blob/main/src/runtime/components/prose/ProsePre.vue
interface Props {
  code?: string
  language?: string
  filename?: string
  highlights?: (() => number[])[]
  meta?: string
  class?: string
}

const props = defineProps<Props>()

const copied = ref(false)

async function handleCopy() {
  if (copied.value || !props.code) return

  await window.navigator.clipboard.writeText(props.code)
  copied.value = true
  setTimeout(() => (copied.value = false), 2000)
}
</script>

<template>
  <pre class="group rounded-2 relative" :class="props.class" v-bind="$attrs">
    <button
      aria-label="copy"
      :class="[
        'rounded-md flex size-8 cursor-pointer flex-center top-2 right-2 absolute transition-all',
        'text-muted-foreground bg-muted/40 opacity-0',
        'group-hover:opacity-100 hover:(text-accent-foreground bg-muted)',
      ]"
      :data-active="copied"
      type="button"
      @click="handleCopy"
    >
      <CopyCheck v-if="copied" class="size-4" />
      <Copy v-else class="size-4" />
    </button>
    <slot></slot>
  </pre>
</template>

// apps/docs-next/src/theme/prose/ProsePre.tsx
'use client'
import type { PropsWithChildren } from 'react'
import type { WithHTMLProps } from '../types'
import { clsx } from '@repo/utils'
import { useState } from 'react'
import { Copy, CopyCheck } from '../icons'

interface Props extends WithHTMLProps<HTMLPreElement> {
  code?: string
  lines?: number
  language: string
  filename?: string
}

export function ProsePre(props: PropsWithChildren<Props>) {
  const { className, code, lines, language, filename, children, ...attrs } =
    props

  const [copied, setCopied] = useState(false)

  async function handleCopy() {
    if (copied || !code) return

    await window.navigator.clipboard.writeText(code)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <pre
      className={clsx('group relative rounded-2', className)}
      data-filename={filename}
      data-language={language}
      data-lines={lines}
      {...attrs}
    >
      <button
        aria-label="copy"
        className={clsx(
          'absolute top-2 right-2 flex size-8 flex-center cursor-pointer rounded-md transition-all',
          'bg-muted/40 text-muted-foreground opacity-0',
          'hover:bg-muted hover:text-accent-foreground group-hover:opacity-100',
          'data-[active=true]:opacity-100'
        )}
        data-active={copied}
        onClick={handleCopy}
        type="button"
      >
        {copied ? <CopyCheck /> : <Copy />}
      </button>
      {children}
    </pre>
  )
}
