// apps/docs-next/src/theme/components/sidebar/SidebarItem.tsx
import type { MenuItem } from '../../types'
import { stylex } from '#/utils'
import { useMenuNodeIsActive } from '../../controller/menus'
import { ChevronRight, Icon } from '../../icons'
import { Accordion, AccordionContent, AccordionTrigger } from '../Accordion'
import { EbbLink } from '../Link'

interface SidebarItemProps {
  item: MenuItem
  level?: number
}

export function SidebarItem(props: SidebarItemProps) {
  const { item, level = 1 } = props

  const isActive = useMenuNodeIsActive(item.index)
  const collapsed = item.collapsed ?? true
  const collapsiable = Array.isArray(item.items) && item.items.length

  if (collapsiable) {
    return (
      <Accordion defaultValue={collapsed}>
        <AccordionTrigger>
          <button
            className="sidebar-item__button"
            data-active={isActive}
            type="button"
          >
            {item.icon && (
              <Icon className="mr-2 h-8 text-brand" icon={item.icon} />
            )}
            <span
              className="flex-1 truncate text-nowrap font-700 text-accent-foreground text-sm leading-8"
              data-role="text"
            >
              {item.text}
            </span>
            <span className="flex size-6 flex-center text-4.5 text-muted-foreground">
              <ChevronRight className="transition-transform duration-300" />
            </span>
          </button>
        </AccordionTrigger>
        <AccordionContent style={stylex({ '--level': level })}>
          {item.items?.map((subItem, index) => (
            <SidebarItem item={subItem} key={index} level={level + 1} />
          ))}
        </AccordionContent>
      </Accordion>
    )
  }

  return (
    <li className="sidebar-item" data-active={isActive} data-role="route">
      <EbbLink
        className="flex items-center gap-2 truncate transition-transform duration-300"
        href={item.link}
      >
        {item.icon && <Icon className="text-brand" icon={item.icon} />}
        <span
          className="flex-1 text-muted-foreground text-sm leading-8 transition-color duration-300 hover:text-brand-2"
          data-role="text"
        >
          {item.text}
        </span>
      </EbbLink>
    </li>
  )
}

// packages/theme/src/components/sidebar/SidebarItem.tsx
import type { MenuItem } from '#/types'
import { computed, defineComponent } from 'vue'
import { Link } from '#/components/Link.tsx'
import { useMenuNodeIsActive } from '#/controller/menus'
import { ChevronRight, Icon } from '#/icons'
import { Accordion, AccordionContent, AccordionTrigger } from '../Accordion.tsx'

export const SidebarItem = defineComponent<{ item: MenuItem; level?: number }>(
  props => {
    const collapsed = props.item.collapsed ?? true
    const collapsiable = computed(() => {
      const item = props.item
      return Array.isArray(item.items) && item.items.length
    })

    const isActive = useMenuNodeIsActive(props.item.index)

    return () => {
      const { item, level = 1 } = props

      if (!collapsiable.value) {
        return (
          <div
            class="sidebar-item"
            data-active={isActive.value}
            data-role="route"
          >
            <Link
              class="flex items-center gap-2 truncate transition-transform duration-300"
              href={item.link}
            >
              {item.icon && <Icon class="text-brand" icon={item.icon} />}
              <span
                class="flex-1 text-muted-foreground text-sm leading-8 transition-color duration-300 hover:text-brand-2"
                data-role="text"
              >
                {item.text}
              </span>
            </Link>
          </div>
        )
      }

      return (
        <Accordion default-value={collapsed}>
          <AccordionTrigger>
            <button
              class="sidebar-item__button"
              data-active={isActive.value}
              type="button"
            >
              {item.icon && (
                <Icon class="mr-2 h-8 text-brand" icon={item.icon} />
              )}
              <span
                class="flex-1 truncate text-nowrap font-700 text-accent-foreground text-sm leading-8"
                data-role="text"
              >
                {item.text}
              </span>
              <span class="flex size-6 flex-center text-4.5 text-muted-foreground">
                <ChevronRight class="transition-transform duration-300" />
              </span>
            </button>
          </AccordionTrigger>
          <AccordionContent style={{ '--level': level }}>
            {item.items?.map((subItem, index) => (
              <SidebarItem item={subItem} key={index} level={level + 1} />
            ))}
          </AccordionContent>
        </Accordion>
      )
    }
  },
  { name: 'SidebarItem', props: ['item', 'level'] }
)
