// apps/docs-next/src/theme/components/Navbar.tsx
import { useRouter } from 'next/navigation'
import { withVars } from '#/utils'
import { EbbAvatar } from '../components/Avatar'
import { useLayout } from '../controller/layout'
import { Menu } from '../icons'
import { useTheme } from '../theme'
import { CubeAvatar } from './CubeAvatar'
import { GlassMask } from './GlassMask'
import { Menubar } from './menubar/Menubar'
import { SocialLinks } from './SocialLinks'
import { SidebarTrigger } from './sidebar/SidebarTrigger'
import { ThemeToggle } from './ThemeToggle'

export function Navbar() {
  return (
    <div
      className="flex flex-center inset-x-0 top-0 fixed z-[--z-index-navbar]"
      data-role="navbar"
    >
      <header className="bg-[--c-bg-navbar] h-[--h-navbar] max-w-320 w-full relative isolate">
        <div className="grid cols-[120px_1fr_120px] size-full">
          <div className="px-6 flex items-center">
            <NavbarBrand />
          </div>

          <div className="flex flex-center">
            <NavbarCenter />
          </div>

          <div className="flex gap-3 items-center">
            <ThemeToggle />
            <SocialLinks />
          </div>
        </div>
      </header>

      <GlassMask
        className="inset-0 absolute -z-1"
        style={withVars({ '--fit-size': 'cover' })}
      />
    </div>
  )
}

function NavbarBrand() {
  const router = useRouter()
  const { theme } = useTheme()
  const { isMobile } = useLayout()

  if (isMobile) {
    return (
      <SidebarTrigger className="text-6 size-10">
        <Menu />
      </SidebarTrigger>
    )
  }

  return (
    <CubeAvatar
      avatar={theme.avatar}
      className="mx-auto"
      onClick={() => router.push('/')}
      style={withVars({
        '--size': '40px',
        '--rounded': '4px'
      })}
    />
  )
}

function NavbarCenter() {
  const router = useRouter()
  const { theme } = useTheme()
  const { isMobile } = useLayout()

  if (isMobile) {
    return <EbbAvatar avatar={theme.avatar} onClick={() => router.push('/')} />
  }

  return <Menubar />
}

// packages/theme/src/components/navbar/Navbar.vue
<script setup lang='ts'>
import { useRouter } from 'nuxt/app'
import { useLayoutCtx } from '#/controller/layout'
import { Menu } from '#/icons'
import { useTheme } from '#/useTheme'
import Avatar from '../Avatar.vue'
import CubeAvatar from '../CubeAvatar.vue'
import GlassMask from '../GlassMask.vue'
import Menubar from '../menubar/Menubar.vue'
import SidebarTrigger from '../sidebar/SidebarTrigger.vue'
import ThemeToggle from '../ThemeToggle.vue'
import SocialLinks from './SocialLinks.vue'

const { isMobile } = useLayoutCtx()
const { theme } = useTheme()

const router = useRouter()

function backHome() {
  router.push('/')
}
</script>

<template>
  <div class="flex flex-center inset-x-0 top-0 fixed z-[--z-index-navbar]" data-role="navbar">
    <header class="bg-[--c-bg-navbar] h-[--h-navbar] max-w-320 w-full relative isolate">
      <div class="grid cols-[120px_1fr_120px] size-full">
        <div class="px-6 flex items-center">
          <SidebarTrigger
            v-if="isMobile"
            class="text-6 size-10"
          >
            <Menu />
          </SidebarTrigger>
          <CubeAvatar
            v-else
            :avatar="theme.avatar"
            class="mx-auto"
            :style="{
              '--size': '40px',
              '--rounded': '4px'
            }"
            @click="backHome"
          />
        </div>

        <div class="flex flex-center">
          <Avatar
            v-if="isMobile"
            :avatar="theme.avatar"
            @click="backHome"
          />
          <Menubar v-else />
        </div>

        <div class="flex gap-3 items-center">
          <ThemeToggle />
          <SocialLinks />
        </div>
      </div>

      <GlassMask class="inset-0 absolute -z-1" style="--fit-size: cover" />
    </header>
  </div>
</template>
