// apps/docs-next/src/theme/components/SocialLinks.tsx
import type { ReactNode } from 'react'
import { useMemo } from 'react'
import { Github } from '../icons'
import { useTheme } from '../theme'
import { EbbLink } from './Link'

const logoMap: Record<string, ReactNode> = {
  github: <Github />
}

export function SocialLinks() {
  const { theme } = useTheme()

  const socialLinks = useMemo(
    () =>
      theme.socialLinks
        ?.filter(item => item.icon in logoMap)
        .map(item => ({
          label: item.icon,
          link: item.link,
          icon: logoMap[item.icon]!
        })) ?? [],
    [theme]
  )

  return (
    <div className="flex gap-2">
      {socialLinks.map(item => (
        <EbbLink
          aria-label={item.label}
          className="flex size-9 flex-center cursor-pointer text-6"
          href={item.link}
          key={item.label}
        >
          {item.icon}
        </EbbLink>
      ))}
    </div>
  )
}

// packages/theme/src/components/navbar/SocialLinks.vue
<script setup lang="ts">
import type { Component } from 'vue'
import { h, shallowRef } from 'vue'
import { Github } from '#/icons'
import { useTheme } from '#/theme'
import Link from '../Link.vue'

const { theme } = useTheme()

const logoMap: Record<string, Component> = {
  github: () => h(Github)
}

const socialLinks = shallowRef(
  theme.socialLinks
    ?.filter(item => item.icon in logoMap)
    .map(item => ({
      label: item.icon,
      link: item.link,
      icon: logoMap[item.icon]!
    })) ?? []
)
</script>

<template>
  <div class="flex gap-2">
    <Link
      v-for="item in socialLinks"
      :key="item.label"
      :aria-label="item.label"
      class="text-6 flex size-9 cursor-pointer flex-center"
      :href="item.link"
    >
      <component :is="item.icon" />
    </Link>
  </div>
</template>
