// packages/theme/src/components/menubar/MenuViewport.vue
<script setup lang='ts'>
import type { ContentView } from '#/controller/navbar.ts'
import { AnimatePresence, motion } from 'motion-v'
import { computed, ref, watch } from 'vue'
import GlassMask from '#/components/GlassMask.vue'
import { ContentRender, useMenubarCtx } from '#/controller/navbar.ts'

const emit = defineEmits<{
  close: []
}>()

const { offsetX, showViewport, contentViews, prevHoverIndex, currHoverIndex } =
  useMenubarCtx()

interface ContentItem extends ContentView {
  show: boolean
  motion?: 'from-start' | 'from-end' | 'to-start' | 'to-end'
}

const contents = ref<ContentItem[]>(
  contentViews.value.map(content => ({
    show: false,
    motion: undefined,
    ...content
  }))
)

watch(currHoverIndex, index => {
  onHoverIndexChange(index, prevHoverIndex.value)
})

const showArrow = computed(
  () => contents.value[currHoverIndex.value]?.item.items?.length
)

function onHoverIndexChange(currIndex: number, prevIndex: number) {
  const currItem = contents.value[currIndex]!
  const prevItem = contents.value[prevIndex]

  const isFromEnd = currIndex > prevIndex
  currItem.motion = isFromEnd ? 'from-end' : 'from-start'
  if (prevItem) {
    prevItem.motion = isFromEnd ? 'to-start' : 'to-end'
  }
  currItem.show = true
}

function onAnimationend(event: AnimationEvent) {
  const target = event.target as HTMLElement
  if (!target.classList.contains('menu-content')) {
    return
  }
  const motion = target.getAttribute('data-motion')!
  if (motion.startsWith('to')) {
    const index = Number(target.getAttribute('data-index'))
    contents.value[index]!.show = false
  }
}

function onExitComplete() {
  !showViewport.value && emit('close')
}
</script>

<template>
  <AnimatePresence @exit-complete="onExitComplete">
    <motion.div
      v-if="showViewport"
      :animate="{ y: 0 }"
      class="menu-viewport"
      :exit="{ opacity: 0, y: 40 }"
      :initial="{ y: 40 }"
      :transition="{
        type: 'spring',
        duration: 0.6
      }"
      @pointermove.stop="() => {}"
    >
      <div class="flex w-full justify-center">
        <div
          v-show="showArrow"
          class="menu-viewport__arrow"
          :style="{ translate: `${offsetX}px 50%` }"
        ></div>
      </div>
      <div class="relative isolate">
        <div
          class="rounded-4 relative overflow-hidden"
          @animationend="onAnimationend"
        >
          <ContentRender
            v-for="(item, index) in contents"
            v-show="item.show"
            :key="index"
            class="menu-content"
            :data-active="currHoverIndex === index"
            :data-index="index"
            :data-motion="item.motion"
            :render="item.render"
          />
        </div>
        <GlassMask class="rounded-4 inset-0 absolute -z-1" />
      </div>
    </motion.div>
  </AnimatePresence>
</template>

// apps/docs-next/src/theme/components/menubar/MenuViewport.tsx
import type { PropsWithChildren } from 'react'
import { AnimatePresence, motion } from 'motion/react'
import { memo, useEffect, useMemo, useState } from 'react'
import { useSharedMenus } from '../../controller/menus'
import { useMenubarCtx } from '../../controller/navbar'
import { GlassMask } from '../GlassMask'
import { MenuViewGroup } from './MenuViewGroup'

interface MenuViewportProps {
  onClose: () => void
}

export function MenuViewport(props: MenuViewportProps) {
  const { offsetX, showViewport, currHoverIndex } = useMenubarCtx()

  const menus = useSharedMenus()
  const contents = useMemo(() => menus.map(item => item.items), [menus])
  const showArrow = !!contents[currHoverIndex]

  function onExitComplete() {
    !showViewport && props.onClose()
  }

  return (
    <AnimatePresence onExitComplete={onExitComplete}>
      {showViewport && (
        <motion.div
          animate={{ y: 0 }}
          className="menu-viewport"
          exit={{ opacity: 0, y: 40 }}
          initial={{ y: 40 }}
          onPointerMove={event => event.stopPropagation()}
          transition={{ type: 'spring', duration: 0.6 }}
        >
          <div className="flex w-full justify-center">
            <div
              className="menu-viewport__arrow"
              style={{
                display: showArrow ? undefined : 'none',
                translate: `${offsetX}px 50%`
              }}
            ></div>
          </div>
          <div className="relative isolate">
            <div className="rounded-4 relative overflow-hidden">
              {contents.map((content, index) => (
                <MenuViewContent index={index} key={index}>
                  {content && <MenuViewGroupMemo items={content} />}
                </MenuViewContent>
              ))}
            </div>
            <GlassMask className="rounded-4 inset-0 absolute -z-1" />
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  )
}

const MenuViewGroupMemo = memo(MenuViewGroup)

type Motion = 'from-start' | 'from-end' | 'to-start' | 'to-end' | undefined

function MenuViewContent(props: PropsWithChildren<{ index: number }>) {
  const { index, children } = props

  const { currHoverIndex, prevHoverIndex } = useMenubarCtx()

  const [show, setShow] = useState(false)
  const [active, setActive] = useState(false)
  const [motion, setMotion] = useState<Motion>(undefined)

  useEffect(() => {
    const isFromEnd = currHoverIndex > prevHoverIndex
    if (index === currHoverIndex) {
      setMotion(isFromEnd ? 'from-end' : 'from-start')
    } else if (index === prevHoverIndex) {
      setMotion(isFromEnd ? 'to-start' : 'to-end')
    }
    setShow(index === currHoverIndex || index === prevHoverIndex)
    setActive(index === currHoverIndex)
  }, [currHoverIndex, prevHoverIndex])

  if (!children) return null

  function onAnimationEnd() {
    if (index === prevHoverIndex) {
      setShow(false)
    }
  }

  return (
    <div
      className="menu-content"
      data-active={active}
      data-index={index}
      data-motion={motion}
      onAnimationEnd={onAnimationEnd}
      style={{ display: show ? undefined : 'none' }}
    >
      {children}
    </div>
  )
}
