// packages/theme/src/components/sidebar/SidebarGroup.vue
<script setup lang='ts'>
import type { SidebarMenuItem } from '#/types'
import { computed } from 'vue'
import { Icon } from '#/icons'
import SidebarItem from './SidebarItem.vue'

const props = defineProps<{
  item: SidebarMenuItem
}>()

const isGrouped = computed(() => !!props.item.grouped)
</script>

<template>
  <section class="sidebar-group" role="group">
    <template v-if="isGrouped">
      <div class="mb-2 px-2 flex">
        <Icon
          v-if="item.icon"
          class="text-18px text-brand mr-2 flex h-8"
          :icon="item.icon"
        />
        <span class="text-14px text-muted-foreground leading-8 font-700">
          {{ item.text }}
        </span>
      </div>
      <section
        v-for="(subItem, index) in item.items"
        :key="index"
        class="py-1"
      >
        <SidebarItem :item="subItem" :level="1" />
      </section>
    </template>
    <SidebarItem v-else :item="item" :level="1" />
  </section>
</template>

// apps/docs-next/src/theme/components/sidebar/SidebarGroup.tsx
import type { SidebarMenuItem } from '../../types'
import { Icon } from '../../icons'
import { SidebarItem } from './SidebarItem'

interface SidebarGroupProps {
  item: SidebarMenuItem
}

export function SidebarGroup({ item }: SidebarGroupProps) {
  const isGrouped = !!item.grouped

  return (
    <section className="sidebar-group" data-role="group">
      {isGrouped ? (
        <>
          <div className="mb-2 px-2 flex">
            {item.icon && (
              <Icon
                className="text-18px text-brand mr-2 flex h-8"
                icon={item.icon}
              />
            )}
            <span className="text-14px text-muted-foreground leading-8 font-700">
              {item.text}
            </span>
          </div>
          {item.items?.map((subItem, index) => (
            <section className="py-1" key={index}>
              <SidebarItem item={subItem} />
            </section>
          ))}
        </>
      ) : (
        <SidebarItem item={item} />
      )}
    </section>
  )
}
