// packages/theme/src/components/sidebar/SidebarTrigger.vue
<script setup lang='ts'>
import { useSidebarControl } from '#/controller/sidebar.ts'

const { isOpen, toggle } = useSidebarControl()
</script>

<template>
  <button
    :aria-checked="isOpen"
    aria-label="sidebar-button"
    class="flex cursor-pointer flex-center"
    role="switch"
    type="button"
    @click="toggle"
  >
    <slot></slot>
  </button>
</template>

// apps/docs-next/src/theme/components/sidebar/SidebarTrigger.tsx
import type { PropsWithChildren } from 'react'
import type { WithHTMLProps } from '../../types'
import { clsx } from '@repo/utils'
import { useSidebarControl } from '../../controller/sidebar'

export function SidebarTrigger(
  props: PropsWithChildren<WithHTMLProps<HTMLButtonElement>>
) {
  const { className, children } = props
  const { isOpen, toggle } = useSidebarControl()

  return (
    <button
      aria-checked={isOpen}
      aria-label="sidebar-button"
      className={clsx('flex cursor-pointer flex-center', className)}
      onClick={toggle}
      role="switch"
      type="button"
    >
      {children}
    </button>
  )
}
