// packages/theme/src/components/sidebar/SidebarItem.vue
<script setup lang='ts'>
import type { MenuItem } from '#/types'
import { computed } from 'vue'
import Link from '#/components/Link.vue'
import { useMenuNodeIsActive } from '#/controller/menus'
import { ChevronRight, Icon } from '#/icons'
import { Accordion, AccordionContent, AccordionTrigger } from '../Accordion.tsx'

interface Props {
  item: MenuItem
  level?: number
}

const props = withDefaults(defineProps<Props>(), { level: 1 })

const collapsed = props.item.collapsed ?? true
const collapsiable = computed(() => {
  const item = props.item
  return Array.isArray(item.items) && item.items.length
})

const isActive = useMenuNodeIsActive(props.item.id)
</script>

<template>
  <Accordion v-if="collapsiable" :default-value="collapsed">
    <AccordionTrigger>
      <button
        class="sidebar-item__button"
        :data-active="isActive"
        type="button"
      >
        <Icon
          v-if="item.icon"
          class="text-brand mr-2 h-8"
          :icon="item.icon"
        />
        <span
          class="text-sm text-accent-foreground leading-8 font-700 flex-1 text-nowrap truncate"
          data-role="button-title"
        >
          {{ item.text }}
        </span>
        <span
          class="text-4.5 text-muted-foreground flex size-6 flex-center"
        >
          <ChevronRight class="transition-transform duration-250" />
        </span>
      </button>
    </AccordionTrigger>
    <AccordionContent :style="{ '--level': level }">
      <SidebarItem
        v-for="(subItem, index) in item.items"
        :key="index"
        :item="subItem"
        :level="level + 1"
      />
    </AccordionContent>
  </Accordion>

  <div
    v-else
    class="sidebar-item"
    :data-active="isActive"
    data-role="route"
  >
    <Link
      class="flex gap-2 truncate transition-transform duration-250 items-center"
      :href="item.link"
    >
      <Icon
        v-if="item.icon"
        class="text-brand"
        :icon="item.icon"
      />
      <span
        class="text-sm text-muted-foreground leading-8 flex-1 transition-color duration-250 hover:text-brand-2"
        data-role="title"
      >
        {{ item.text }}
      </span>
    </Link>
  </div>
</template>

// apps/docs-next/src/theme/components/sidebar/SidebarItem.tsx
import type { MenuItem } from '../../types'
import { stylex } from '#/utils'
import { useMenuNodeIsActive } from '../../controller/menus'
import { ChevronRight, Icon } from '../../icons'
import { Accordion, AccordionContent, AccordionTrigger } from '../Accordion'
import { EbbLink } from '../Link'

interface SidebarItemProps {
  item: MenuItem
  level?: number
}

export function SidebarItem(props: SidebarItemProps) {
  const { item, level = 1 } = props

  const isActive = useMenuNodeIsActive(item.index)
  const collapsed = item.collapsed ?? true
  const collapsiable = Array.isArray(item.items) && item.items.length

  if (collapsiable) {
    return (
      <Accordion defaultValue={collapsed}>
        <AccordionTrigger>
          <button
            className="sidebar-item__button"
            data-active={isActive}
            type="button"
          >
            {item.icon && (
              <Icon className="text-brand mr-2 h-8" icon={item.icon} />
            )}
            <span
              className="text-sm text-accent-foreground leading-8 font-700 flex-1 text-nowrap truncate"
              data-role="text"
            >
              {item.text}
            </span>
            <span className="text-4.5 text-muted-foreground flex size-6 flex-center">
              <ChevronRight className="transition-transform duration-300" />
            </span>
          </button>
        </AccordionTrigger>
        <AccordionContent style={stylex({ '--level': level })}>
          {item.items?.map((subItem, index) => (
            <SidebarItem item={subItem} key={index} level={level + 1} />
          ))}
        </AccordionContent>
      </Accordion>
    )
  }

  return (
    <li className="sidebar-item" data-active={isActive} data-role="route">
      <EbbLink
        className="flex gap-2 truncate transition-transform duration-300 items-center"
        href={item.link}
      >
        {item.icon && <Icon className="text-brand" icon={item.icon} />}
        <span
          className="text-sm text-muted-foreground leading-8 flex-1 transition-color duration-300 hover:text-brand-2"
          data-role="title"
        >
          {item.text}
        </span>
      </EbbLink>
    </li>
  )
}
