// packages/ui/src/components/sidebar/SidebarItem.vue
<script setup lang='ts'>
import type { SidebarItem as SidebarItemProp } from '#/types'
import { AnimatePresence, motion } from 'motion-v'
import { computed, ref } from 'vue'
import Link from '#/core/Link.vue'
import { ChevronRight } from '#/icons'

interface Props {
  item: SidebarItemProp
  level?: number
}

const props = withDefaults(defineProps<Props>(), { level: 1 })

const hasChildren = computed(() => {
  const items = props.item.items
  return Array.isArray(items) && items.length
})

const collapsed = ref(props.item.collapsed ?? true)
const collapsiable = computed(
  () => props.item.collapsed !== undefined && hasChildren.value
)

function toggle() {
  if (collapsiable.value) {
    collapsed.value = !collapsed.value
  }
}
</script>

<template>
  <section>
    <button
      v-if="collapsiable"
      :aria-expanded="!collapsed"
      class="group/sidebar-btn text-left flex w-full cursor-pointer"
      type="button"
      @click="toggle"
    >
      <span class="text-sm text-[--c-text-1] leading-8 font-700 flex-1 text-nowrap truncate">
        {{ item.text }}
      </span>
      <span
        class="text-(lg [--c-text-3]) flex size-8 flex-center group-hover/sidebar-btn:text-[--c-text-2] -mr-2"
      >
        <ChevronRight
          class="transition-transform duration-250 group-aria-[expanded=true]/sidebar-btn:rotate-90"
        />
      </span>
    </button>

    <Link
      v-else
      class="group/sidebar-link py-1 flex w-full cursor-pointer text-nowrap truncate"
      :data-active="item.acitve"
      data-role="link"
      :href="item.link"
    >
      <span
        :class="[
          'flex-1',
          'text-(sm [--c-text-2]) leading-8 font-500',
          'transition-color duration-250',
          'hover:text-[--c-brand-1]',
          'group-data-[active=true]/sidebar-link:text-[--c-brand-1]',
        ]"
      >
        {{ item.text }}
      </span>
    </Link>

    <template v-if="hasChildren">
      <AnimatePresence>
        <motion.div
          v-show="!collapsed"
          :animate="{ height: 'auto' }"
          class="mt-2 pl-5 border-l border-[--c-divider] overflow-hidden"
          :exit="{ height: 0 }"
          :style="{ '--level': level }"
          :transition="{ ease: 'easeIn' }"
        >
          <SidebarItem
            v-for="(subItem, index) in item.items"
            :key="index"
            :item="subItem"
            :level="level + 1"
          />
        </motion.div>
      </AnimatePresence>
    </template>
  </section>
</template>

// apps/docs-next/src/theme/components/sidebar/SidebarItem.tsx
import type { SidebarMenuItem } from '../../types'
import { useEffect, useRef, useState } from 'react'
import { ChevronRight, Icon } from '../../icons'
import { EbbLink } from '../Link'

interface SidebarItemProps {
  item: SidebarMenuItem
  level?: number
}

export function SidebarItem(props: SidebarItemProps) {
  const { item, level = 1 } = props

  const [collapsed, setCollapsed] = useState(item.collapsed ?? true)
  const collapsiable = Array.isArray(item.items) && item.items.length

  const viewRef = useRef<HTMLDivElement | null>(null)

  function toggle() {
    const element = viewRef.current!
    if (collapsed) {
      setCollapsed(false)
      element.style.removeProperty('display')
      element.style.height = element.scrollHeight + 'px'
    } else {
      setCollapsed(true)
      element.style.height = '0'
    }
  }

  function onTransitionEnd(event: any) {
    event.stopPropagation()
    if (collapsed) {
      const element = viewRef.current!
      element.style.setProperty('display', 'none')
    }
  }

  useEffect(() => {
    const element = viewRef.current
    if (element && collapsed) {
      element.style.display = 'none'
      element.style.height = '0'
    }
  }, [])

  if (collapsiable) {
    return (
      <>
        <button
          aria-expanded={!collapsed}
          className="sidebar-item__button"
          data-active={item.active}
          onClick={toggle}
          type="button"
        >
          {item.icon && (
            <Icon className="text-brand mr-2 h-8" icon={item.icon} />
          )}
          <span
            className="text-sm text-accent-foreground leading-8 font-700 flex-1 text-nowrap truncate"
            data-role="button-title"
          >
            {item.text}
          </span>
          <span className="text-4.5 text-muted-foreground flex size-6 flex-center">
            <ChevronRight className="transition-transform duration-250" />
          </span>
        </button>
        <div
          className="pl-5 transition-height duration-250 ease overflow-hidden"
          data-level={level}
          onTransitionEnd={onTransitionEnd}
          ref={viewRef}
        >
          {item.items!.map((subItem, index) => (
            <SidebarItem item={subItem} key={index} level={level + 1} />
          ))}
        </div>
      </>
    )
  }

  return (
    <div className="sidebar-item" data-active={item.active} data-role="route">
      <EbbLink className="flex gap-2 truncate items-center" href={item.link!}>
        {item.icon && <Icon className="text-brand" icon={item.icon} />}
        <span
          className="text-sm text-muted-foreground leading-8 flex-1 transition-color duration-250 hover:text-brand-2"
          data-role="title"
        >
          {item.text}
        </span>
      </EbbLink>
    </div>
  )
}
