// apps/docs-next/src/theme/prose/ProseA.tsx
'use client'
import type { PropsWithChildren } from 'react'
import { EbbLink } from '../components/Link'

interface Props {
  href: string
  target?: string
}

export function ProseA(props: PropsWithChildren<Props>) {
  const { href, target, children } = props
  return (
    <EbbLink className="ebb-link relative" href={href} target={target}>
      {children}
    </EbbLink>
  )
}

// packages/theme/src/prose/ProseA.tsx
import type { FunctionalComponent } from 'vue'

interface Props {
  href: string
  target?: string
}

export const ProseA: FunctionalComponent<Props> = (props, { slots }) => {
  const { href, target } = props
  return (
    <a class="ebb-link relative" href={href} target={target}>
      {slots.default?.()}
    </a>
  )
}
