// apps/docs-next/src/app/docs/archive/page.tsx
import type { Metadata } from 'next'
import { formatTitle } from '#/utils'
import { getArchiveData } from './_data'
import { TransitionLink } from './Link'
import 'ebb-ui/pages/archive.css'

export const metadata: Metadata = {
  title: formatTitle('归档'),
  description: '潮起潮落-归档'
}

export default async function Page() {
  const articles = await getArchiveData()

  return (
    <div className="archive-page">
      <div className="chain top-[--offset]"></div>
      <div className="chain bottom-[--offset]" data-reverse="true"></div>
      <div className="cards-container">
        <ul className="cards">
          {articles.map((item, index) => (
            <li key={index}>
              <TransitionLink to={`/docs/${item.path}`}>
                <picture className="overflow-hidden">
                  <img alt="img" loading="lazy" src={item.cover} />
                </picture>
                <div className="p-2 bg-black">
                  <p className="leading-6 font-bold mb-2 text-center truncate">
                    {item.title}
                  </p>
                </div>
                <div className="p-2 bg-black/60 inset-x-0 bottom-10 absolute">
                  <p className="text-xs flex gap-2 items-center">
                    {item.tags?.map((tag, idx) => (
                      <span key={idx}>{`#${tag}`}</span>
                    ))}
                    <span className="flex-1"></span>
                  </p>
                </div>
                <div
                  className="card-mask inset-0 absolute z-10"
                  data-role="mask"
                ></div>
              </TransitionLink>
            </li>
          ))}
        </ul>
      </div>
    </div>
  )
}

// apps/docs/app/pages/archive.vue
<script setup lang='ts'>
import 'ebb-ui/pages/archive.css'

useSeoMeta({
  title: formatTitle('归档'),
  description: '潮起潮落-归档'
})

const articles = await useFetch('/api/archive').then(
  res => res.data.value?.data
)
</script>

<template>
  <div class="archive-page">
    <div class="chain top-[--offset]"></div>
    <div class="chain bottom-[--offset]" data-reverse="true"></div>
    <div class="cards-container">
      <ul class="cards">
        <li v-for="(item, index) in articles" :key="index">
          <NuxtLink class="card relative" :to="item.path">
            <picture class="overflow-hidden">
              <img alt="img" loading="lazy" :src="item.cover" />
            </picture>
            <div class="p-2 bg-black">
              <p class="leading-6 font-bold mb-2 text-center truncate">
                {{ item.title }}
              </p>
            </div>
            <div class="p-2 bg-black/60 inset-x-0 bottom-10 absolute">
              <p class="text-xs flex gap-2 items-center">
                <span v-for="(tag, idx) in item.tags" :key="idx">
                  {{ '#' + tag }}
                </span>
                <span class="flex-1"></span>
                <NuxtTime
                  class="text-xs text-muted-foreground"
                  :datetime="item.lastUpdated"
                />
              </p>
            </div>
            <div class="card-mask inset-0 absolute z-10" data-role="mask"></div>
          </NuxtLink>
        </li>
      </ul>
    </div>
  </div>
</template>
