// apps/docs-next/src/theme/components/menubar/Menubar.tsx
import type { ViewportRef } from './MenuViewport'
import { LayoutGroup, animate, motion, useMotionValue } from 'motion/react'
import { memo, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { stylex } from '#/utils'
import { useMenuActiveNode, useSharedMenus } from '../../controller/menus'
import {
  MenubarProvider,
  MotionProvider,
  useMenubarMotion,
  useMotion
} from '../../controller/navbar'
import { FlowingLight } from '../FlowingLight'
import { MenubarItem } from './MenubarItem'
import { MenuViewport } from './MenuViewport'

const MenubarItemMemo = memo(MenubarItem, () => true)

type HoverChangeCallback = (index: number) => void

export function Menubar() {
  const menus = useSharedMenus()
  const currActiveNode = useMenuActiveNode()
  const { scope, updateMotion, onMotionChange } = useMenubarMotion()

  const activeIndex = useRef(-1)
  const viewportRef = useRef<ViewportRef>(undefined!)
  const hoverChangeCbs = useRef<HoverChangeCallback[]>([])

  useEffect(() => {
    const prevActiveIndex = activeIndex.current

    let activeNode = currActiveNode
    while (activeNode?.parent) {
      activeNode = activeNode.parent
    }

    const index = menus.indexOf(activeNode!)
    if (prevActiveIndex !== index) {
      activeIndex.current = index
      updateMotion(index)
    }
  }, [currActiveNode])

  const onMenuItemHover = useCallback((index: number) => {
    updateMotion(index)
    for (const cb of hoverChangeCbs.current) {
      cb(index)
    }
  }, [])

  const onHoverIndexChange = useCallback((callback: HoverChangeCallback) => {
    hoverChangeCbs.current.push(callback)
  }, [])

  function onMouseEnter() {
    viewportRef.current.open()
  }

  function onMouseLeave() {
    viewportRef.current.close()
  }

  function onViewportClose() {
    updateMotion(activeIndex.current)
  }

  const motionValue = useMemo(
    () => ({
      onMotionChange
    }),
    [onMotionChange]
  )

  const contextValue = useMemo(
    () => ({
      onMenuItemHover,
      onHoverIndexChange
    }),
    [onMenuItemHover, onHoverIndexChange]
  )

  return (
    <nav className="menubar" onPointerLeave={onMouseLeave} ref={scope}>
      <MotionProvider value={motionValue}>
        <MenubarBackground />
        <MenubarIndicator />
      </MotionProvider>

      <MenubarProvider value={contextValue}>
        <menu
          className="grid-full px-4 flex"
          data-role="menu"
          onPointerEnter={onMouseEnter}
        >
          <LayoutGroup>
            {menus.map((item, index) => (
              <MenubarItemMemo index={index} item={item} key={item.id} />
            ))}
          </LayoutGroup>
        </menu>
        <MenuViewport onClose={onViewportClose} ref={viewportRef} />
      </MenubarProvider>

      <FlowingLight />
    </nav>
  )
}

function MenubarBackground() {
  const [offsetX, setOffsetX] = useState(0)
  const { onMotionChange } = useMotion()

  useEffect(() => {
    onMotionChange(motion => {
      setOffsetX(motion.offsetX)
    })
  }, [])

  return (
    <div
      aria-hidden="true"
      className="menubar-background"
      data-role="background"
      style={stylex({ '--offset-x': offsetX + 'px' })}
    ></div>
  )
}

function MenubarIndicator() {
  const motionX = useMotionValue(0)
  const motionW = useMotionValue(0)
  const { onMotionChange } = useMotion()

  useEffect(() => {
    onMotionChange(motion => {
      const { offsetX, itemWidth } = motion
      animate(motionX, offsetX, { type: 'spring', duration: 0.6 })
      animate(motionW, itemWidth, { type: 'spring', duration: 0.6 })
    })
  }, [])

  return (
    <motion.div
      aria-hidden="true"
      className="rounded-[--rounded] h-8 absolute -z-1"
      data-role="indicator"
      style={{
        x: motionX,
        width: motionW,
        boxShadow: 'inset 0 0 12px 1px hsl(187 75% 65% / 0.4)'
      }}
    />
  )
}

// packages/theme/src/components/menubar/Menubar.tsx
import type { MenuViewportRef } from './MenuViewport'
import { LayoutGroup, animate, motion, useMotionValue } from 'motion-v'
import { defineComponent, ref, shallowRef, watch } from 'vue'
import { useCurrActiveNode, useMenus } from '#/controller/menus'
import {
  MenubarProvider,
  MotionProvider,
  useMenubarMotion,
  useMotionCtx
} from '#/controller/navbar'
import FlowingLight from '../FlowingLight.vue'
import MenubarItem from './MenubarItem.vue'
import MenuViewport from './MenuViewport.tsx'

type HoverChangeCallback = (index: number) => void

export default defineComponent(
  () => {
    const menus = useMenus()
    const currActiveNode = useCurrActiveNode()
    const { scope, updateMotion, onMotionChange } = useMenubarMotion()

    const viewportRef = shallowRef<MenuViewportRef>(null!)
    const onHoverCbs: HoverChangeCallback[] = []
    let activeIndex = -1

    watch(
      () => currActiveNode.value,
      () => {
        const prevActiveIndex = activeIndex
        let activeNode = currActiveNode.value
        while (activeNode?.parent) {
          activeNode = activeNode.parent
        }

        const index = menus.value.indexOf(activeNode!)
        if (prevActiveIndex !== index) {
          activeIndex = index
          updateMotion(index)
        }
      },
      { immediate: true }
    )

    function onMenuItemHover(index: number) {
      updateMotion(index)
      for (const cb of onHoverCbs) {
        cb(index)
      }
    }

    function onHoverIndexChange(callback: HoverChangeCallback) {
      onHoverCbs.push(callback)
    }

    function onMouseEnter() {
      viewportRef.value.open()
    }

    function onMouseLeave() {
      viewportRef.value.close()
    }

    function onViewportClose() {
      updateMotion(activeIndex)
    }

    const motionValue = { onMotionChange }
    const contextValue = { onMenuItemHover, onHoverIndexChange }

    return () => (
      <nav
        class="menubar"
        data-role="menubar"
        onPointerleave={onMouseLeave}
        ref={scope}
      >
        <MotionProvider value={motionValue}>
          <MenubarBackground />
          <MenubarIndicator />
        </MotionProvider>

        <MenubarProvider value={contextValue}>
          <menu
            class="grid-full px-4 flex"
            data-role="menu"
            onPointerenter={onMouseEnter}
          >
            <LayoutGroup>
              {menus.value.map((item, index) => (
                <MenubarItem index={index} item={item} key={item.id} />
              ))}
            </LayoutGroup>
          </menu>
          {<MenuViewport onClose={onViewportClose} ref={viewportRef} />}
        </MenubarProvider>

        <FlowingLight />
      </nav>
    )
  },
  { name: 'Menubar' }
)

const MenubarBackground = defineComponent(() => {
  const offsetX = ref(0)
  const { onMotionChange } = useMotionCtx()

  onMotionChange(motion => (offsetX.value = motion.offsetX))

  return () => (
    <div
      aria-hidden="true"
      class="menubar-background"
      data-role="background"
      style={{ '--offset-x': offsetX.value + 'px' }}
    ></div>
  )
})

const MenubarIndicator = defineComponent(() => {
  const motionX = useMotionValue(0)
  const motionW = useMotionValue(0)
  const { onMotionChange } = useMotionCtx()

  onMotionChange(motion => {
    const { offsetX, itemWidth } = motion
    animate(motionX, offsetX, { type: 'spring', duration: 0.6 })
    animate(motionW, itemWidth, { type: 'spring', duration: 0.6 })
  })

  return () => (
    <motion.div
      aria-hidden="true"
      class="rounded-[--rounded] h-8 absolute -z-1"
      data-role="indicator"
      style={{
        x: motionX,
        width: motionW,
        boxShadow: 'inset 0 0 12px 1px hsl(187 75% 65% / 0.4)'
      }}
    />
  )
})
