// apps/docs-next/src/theme/components/menubar/MenuViewport.tsx
import type { PropsWithChildren, RefObject } from 'react'
import { AnimatePresence, motion } from 'motion/react'
import {
  memo,
  useEffect,
  useEffectEvent,
  useImperativeHandle,
  useMemo,
  useState
} from 'react'
import { stylex } from '#/utils'
import { useMenus } from '../../controller/menus'
import {
  useMenubar,
  useViewport,
  ViewportProvider
} from '../../controller/navbar'
import { GlassMask } from '../Effect'
import { MenuViewGroup } from './MenuViewGroup'

export interface ViewportRef {
  open: () => void
  close: () => void
}

interface MenuViewportProps {
  ref: RefObject<ViewportRef>
  onClose: () => void
}

export function MenuViewport(props: MenuViewportProps) {
  const menus = useMenus()
  const contents = useMemo(() => menus.map(item => item.items), [menus])

  const { onHoverIndexChange } = useMenubar()

  const [show, setShow] = useState(false)
  const [prevIndex, setPrevIndex] = useState(-1)
  const [currIndex, setCurrIndex] = useState(-1)

  const handleIndexChange = useEffectEvent((index: number) => {
    setPrevIndex(currIndex)
    setCurrIndex(index)
  })

  useEffect(() => {
    onHoverIndexChange(handleIndexChange)
  }, [])

  useImperativeHandle(
    props.ref,
    () => ({
      open: () => setShow(true),
      close: () => setShow(false)
    }),
    []
  )

  function onExitComplete() {
    !show && props.onClose()
  }

  const contextValue = { prevIndex, currIndex }

  return (
    <AnimatePresence onExitComplete={onExitComplete}>
      {show && (
        <motion.div
          animate={{ y: 0 }}
          className="pt-2 min-w-full contain-layout left-1/2 top-full absolute isolate -translate-x-1/2"
          data-role="viewport"
          exit={{ opacity: 0, y: 40 }}
          initial={{ y: 40 }}
          transition={{ type: 'spring', duration: 0.6 }}
        >
          <div className="relative isolate">
            <ViewportProvider value={contextValue}>
              <div className="rounded-4 relative overflow-hidden">
                {contents.map((content, index) => (
                  <MenuViewContent index={index} key={index}>
                    {content && <MenuViewGroupMemo items={content} />}
                  </MenuViewContent>
                ))}
              </div>
            </ViewportProvider>
            <GlassMask className="rounded-4 inset-0 absolute -z-1" />
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  )
}

const MenuViewGroupMemo = memo(MenuViewGroup)

type Motion = 'from-start' | 'from-end' | 'to-start' | 'to-end' | undefined

function MenuViewContent(props: PropsWithChildren<{ index: number }>) {
  const { index, children } = props

  const { currIndex, prevIndex } = useViewport()

  const [show, setShow] = useState(false)
  const [active, setActive] = useState(false)
  const [motion, setMotion] = useState<Motion>(undefined)

  useEffect(() => {
    const isFromEnd = currIndex > prevIndex
    if (index === currIndex) {
      setMotion(isFromEnd ? 'from-end' : 'from-start')
    } else if (index === prevIndex) {
      setMotion(isFromEnd ? 'to-start' : 'to-end')
    }
    setShow(index === currIndex || index === prevIndex)
    setActive(index === currIndex)
  }, [currIndex, prevIndex])

  if (!children) return null

  function onAnimationEnd() {
    if (index === currIndex) {
      return
    }
    if (index === prevIndex) {
      setShow(false)
    }
  }

  return (
    <div
      className="menu-content"
      data-active={active}
      data-index={index}
      data-motion={motion}
      onAnimationEnd={onAnimationEnd}
      style={stylex({ display: !show && 'none' })}
    >
      {children}
    </div>
  )
}

// packages/theme/src/components/menubar/MenuViewport.tsx
import { AnimatePresence, motion } from 'motion-v'
import { computed, defineComponent, defineExpose, ref, watch } from 'vue'
import { useMenus } from '#/controller/menus'
import { ViewportProvider, useMenubar, useViewport } from '#/controller/navbar'
import GlassMask from '../GlassMask.vue'
import MenuViewGroup from './MenuViewGroup.vue'

export const MenuViewport = defineComponent<any, { close: () => void }>(
  (_, { emit }) => {
    const menus = useMenus()
    const contents = computed(() => menus.value.map(item => item.items))

    const { onHoverIndexChange } = useMenubar()

    const show = ref(false)
    const prevIndex = ref(-1)
    const currIndex = ref(-1)

    function handleIndexChange(index: number) {
      prevIndex.value = currIndex.value
      currIndex.value = index
    }

    onHoverIndexChange(handleIndexChange)

    function onExitComplete() {
      !show.value && emit('close')
    }

    const contextValue = { prevIndex, currIndex }

    defineExpose({
      open: () => (show.value = true),
      close: () => (show.value = false)
    })

    return () => (
      <AnimatePresence onExitComplete={onExitComplete}>
        {show && (
          <motion.div
            animate={{ y: 0 }}
            class="pt-2 min-w-full contain-layout left-1/2 top-full absolute isolate -translate-x-1/2"
            data-role="viewport"
            exit={{ opacity: 0, y: 40 }}
            initial={{ y: 40 }}
            transition={{ type: 'spring', duration: 0.6 }}
          >
            <div class="relative isolate">
              <ViewportProvider value={contextValue}>
                <div class="rounded-4 relative overflow-hidden">
                  {contents.value.map((content, index) => (
                    <MenuViewContent index={index} key={index}>
                      {content && <MenuViewGroup items={content} />}
                    </MenuViewContent>
                  ))}
                </div>
              </ViewportProvider>
              <GlassMask class="rounded-4 inset-0 absolute -z-1" />
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    )
  },
  { emits: ['close'] }
)

type Motion = 'from-start' | 'from-end' | 'to-start' | 'to-end' | undefined

const MenuViewContent = defineComponent<{ index: number }>(
  (props, { slots }) => {
    const { currIndex, prevIndex } = useViewport()

    const show = ref(false)
    const active = ref(false)
    const motion = ref<Motion>(undefined)

    watch(
      () => [currIndex.value, prevIndex.value],
      value => {
        const [currIndex, prevIndex] = value as [number, number]
        const isFromEnd = currIndex > prevIndex
        const index = props.index
        if (index === currIndex) {
          motion.value = isFromEnd ? 'from-end' : 'from-start'
        } else if (index === prevIndex) {
          motion.value = isFromEnd ? 'to-start' : 'to-end'
        }
        show.value = index === currIndex || index === prevIndex
        active.value = index === currIndex
      }
    )

    function onAnimationEnd() {
      if (props.index === currIndex.value) {
        return
      }
      if (props.index === prevIndex.value) {
        show.value = false
      }
    }

    return () => {
      const children = slots.default?.()
      if (!children) return null
      return (
        <div
          class="menu-content"
          data-active={active.value}
          data-index={props.index}
          data-motion={motion.value}
          onAnimationend={onAnimationEnd}
          style={!show && { display: 'none' }}
        ></div>
      )
    }
  },
  { props: ['index'] }
)
