// packages/ui/src/components/widgets/Avatar.vue
<script setup lang="ts">
</script>

<template>
  <button
    aria-label="home-button"
    class="cursor-pointer drop-shadow-sm drop-shadow-color-cyan-300"
    type="button"
  >
    <div class="mask mask-squircle">
      <img
        alt="site owner avatar"
        class="size-[44px]"
        decoding="async"
        src="https://antik-0.github.io/ebb-and-flow/assets/EAF-avatar.CHiAdHFK.png"
      />
    </div>
  </button>
</template>

// packages/theme-ebb/src/components/Avatar.tsx
import type { WithHTMLProps } from '#/types'
import { clsx } from '@repo/utils'

interface Props extends WithHTMLProps<HTMLButtonElement> {
  avatar: string
}

export function EbbAvatar(props: Props) {
  const { avatar, className, ...restProps } = props

  return (
    <button
      aria-label="avatar"
      className={clsx(
        'cursor-pointer drop-shadow-sm drop-shadow-color-cyan-300',
        className
      )}
      type="button"
      {...restProps}
    >
      <div className="mask mask-squircle">
        <img
          alt="site owner avatar"
          className="size-11"
          decoding="async"
          src={avatar}
        />
      </div>
    </button>
  )
}
