// packages/theme/src/components/Link.tsx
import { isExternalLink } from '@repo/utils'
import { computed, defineComponent, h, resolveComponent } from 'vue'

export const Link = defineComponent<{ href?: string }>(
  (props, { slots, attrs }) => {
    const NuxtLink = resolveComponent('NuxtLink')

    const isExternal = computed(() => isExternalLink(props.href ?? ''))
    const target = computed(() => (isExternal.value ? '_blank' : undefined))
    const rel = computed(() => (isExternal.value ? 'noreferrer' : undefined))

    return () => {
      if (!props.href) {
        return h('span', { ...attrs }, slots.default?.())
      }

      return h(
        NuxtLink,
        {
          rel: rel.value,
          href: props.href,
          target: target.value,
          ...attrs
        },
        () => slots.default?.()
      )
    }
  },
  { name: 'EbbLink', props: ['href'] }
)

// apps/docs-next/src/theme/components/Link.tsx
import type { LinkProps as NextLinkProps } from 'next/link'
import type { PropsWithChildren } from 'react'
import type { WithHTMLProps } from '../types'
import { isExternalLink, isString } from '@repo/utils'
import NextLink from 'next/link'

interface EbbLinkProps
  extends Omit<NextLinkProps, 'href'>, WithHTMLProps<HTMLAnchorElement> {
  href?: NextLinkProps['href']
}

export function EbbLink(props: PropsWithChildren<EbbLinkProps>) {
  const {
    href,
    replace,
    scroll,
    prefetch,
    onNavigate,
    children,
    rel,
    ...attrs
  } = props

  const _href = isString(href) ? href : (href?.pathname ?? '')
  const isExternal = isExternalLink(_href)
  const target = isExternal ? '_blank' : undefined
  const ref = isExternal ? 'noreferrer' : undefined

  if (isExternal) {
    return (
      <a href={_href} rel={ref} target={target} {...attrs}>
        {children}
      </a>
    )
  }

  return (
    <NextLink
      href={_href}
      onNavigate={onNavigate}
      prefetch={prefetch}
      rel={rel}
      replace={replace}
      scroll={scroll}
      target={target}
      {...attrs}
    >
      {children}
    </NextLink>
  )
}
