// packages/theme/src/components/Navbar.tsx
import type { Component } from 'vue'
import type { SocialLink } from '#/types'
import { navigateTo } from 'nuxt/app'
import { defineComponent, h } from 'vue'
import { useLayout } from '#/controller/layout'
import { Github, Menu } from '#/icons'
import { useEbbTheme } from '#/theme'
import { Avatar, CubeAvatar, GlassMask } from './Effect.tsx'
import { Link } from './Link.tsx'
import { Menubar } from './menubar/Menubar.tsx'
import { SidebarTrigger } from './sidebar/Sidebar.tsx'
import { ThemeToggle } from './ThemeToggle.tsx'

export const Navbar = defineComponent(
  () => {
    const theme = useEbbTheme()
    const { isMobile } = useLayout()

    return () => (
      <header
        class="grid-area-[navbar] fixed inset-x-0 top-0 z-[--z-index-navbar] flex flex-center"
        data-role="navbar"
      >
        <div class="cols-[120px_1fr_120px] grid h-[--h-navbar] w-full max-w-320">
          <div class="flex items-center px-4">
            <NavbarAction avatar={theme.avatar} isMobile={isMobile.value} />
          </div>

          <div class="flex flex-center">
            <Avatar
              avatar={theme.avatar}
              data-role="site-logo"
              onClick={() => navigateTo('/')}
            />
            <Menubar />
          </div>

          <div class="flex items-center justify-end gap-2 pr-4">
            <ThemeToggle />
            <SocialLinks items={theme.socialLinks} />
          </div>
        </div>

        <GlassMask class="absolute inset-0 -z-1" />
      </header>
    )
  },
  { name: 'Navbar' }
)

function NavbarAction(props: { avatar: string; isMobile: boolean }) {
  const { avatar, isMobile } = props

  if (isMobile) {
    return (
      <SidebarTrigger class="size-10 text-6">
        <Menu />
      </SidebarTrigger>
    )
  }

  return h(CubeAvatar, {
    avatar,
    class: 'mx-auto',
    style: { '--size': '40px', '--rounded': '4px' },
    onClick: () => navigateTo('/')
  })
}
NavbarAction.props = ['avatar', 'isMobile']

const logoMap: Record<string, Component> = {
  github: Github
}

function SocialLinks(props: { items?: SocialLink[] }) {
  const links =
    props.items
      ?.filter(item => item.icon in logoMap)
      .map(item => ({
        label: item.icon,
        link: item.link,
        icon: logoMap[item.icon]!
      })) ?? []

  return (
    <div class="flex gap-2">
      {links.map(item => (
        <Link
          aria-label={item.label}
          class="flex size-9 flex-center cursor-pointer text-6"
          href={item.link}
          key={item.label}
        >
          {h(item.icon)}
        </Link>
      ))}
    </div>
  )
}
SocialLinks.props = ['items']

// apps/docs-next/src/theme/components/Navbar.tsx
'use client'
import { useRouter } from 'next/navigation'
import { stylex } from '#/utils'
import { useLayout } from '../controller/layout'
import { Menu } from '../icons'
import { useTheme } from '../theme'
import { Avatar, CubeAvatar, GlassMask } from './Effect'
import { Menubar } from './menubar/Menubar'
import { SocialLinks } from './SocialLinks'
import { SidebarTrigger } from './sidebar/SidebarTrigger'
import { ThemeToggle } from './ThemeToggle'

export function Navbar() {
  return (
    <div
      className="flex grid-area-[navbar] flex-center inset-x-0 top-0 fixed z-[--z-index-navbar]"
      data-role="navbar"
    >
      <header className="grid cols-[120px_1fr_120px] h-[--h-navbar] max-w-320 w-full">
        <div className="px-4 flex items-center">
          <NavbarAction />
        </div>

        <div className="flex flex-center">
          <NavbarCenter />
        </div>

        <div className="pr-4 flex gap-2 items-center justify-end">
          <ThemeToggle />
          <SocialLinks />
        </div>
      </header>

      <GlassMask className="inset-0 absolute -z-1" />
    </div>
  )
}

function NavbarAction() {
  const router = useRouter()
  const { theme } = useTheme()
  const isMobile = useLayout(state => state.isMobile)

  if (isMobile) {
    return (
      <SidebarTrigger className="text-6 size-10">
        <Menu />
      </SidebarTrigger>
    )
  }

  return (
    <CubeAvatar
      avatar={theme.avatar}
      className="mx-auto"
      onClick={() => router.push('/')}
      style={stylex({ '--size': '40px', '--rounded': '4px' })}
    />
  )
}

function NavbarCenter() {
  const router = useRouter()
  const { theme } = useTheme()

  return (
    <>
      <Avatar
        avatar={theme.avatar}
        data-role="site-logo"
        onClick={() => router.push('/')}
      />
      <Menubar />
    </>
  )
}
