// packages/theme/src/components/ThemeToggle.vue
<script setup lang='ts'>
import { motion } from 'motion-v'
import { shallowRef } from 'vue'
import { ThemeDark, ThemeLight } from '#/icons'

const isDark = shallowRef(true)

function toggle() {
  isDark.value = !isDark.value
}
</script>

<template>
  <motion.button
    :aria-checked="isDark"
    aria-label="dark-toggle"
    :class="[
      'text-5 border border-divider bg-[--c-bg-mutate]/20',
      'flex items-center p-0.5 rounded-4 w-12 cursor-pointer',
    ]"
    :data-state="isDark ? 'dark' : 'light'"
    role="switch"
    :style="{ justifyContent: isDark ? 'flex-end' : 'flex-start' }"
    type="button"
    @click="toggle"
  >
    <motion.span
      :transition="{
        type: 'spring',
        visualDuration: 0.8,
      }"
      layout
    >
      <ThemeDark v-if="isDark" />
      <ThemeLight v-else />
    </motion.span>
  </motion.button>
</template>

// apps/docs-next/src/theme/components/ThemeToggle.tsx
import { clsx } from '@repo/utils'
import { motion } from 'motion/react'
import { useState } from 'react'
import { ThemeDark, ThemeLight } from '../icons'

export function ThemeToggle() {
  const [isDark, setDark] = useState(true)

  function toggle() {
    setDark(value => !value)
  }

  return (
    <motion.button
      aria-checked={isDark}
      aria-label="dark-toggle"
      className={clsx(
        'text-5 border border-divider bg-[--c-bg-mutate]/20',
        'p-0.5 rounded-4 flex w-12 cursor-pointer items-center'
      )}
      data-state={isDark ? 'dark' : 'light'}
      onClick={toggle}
      role="switch"
      style={{ justifyContent: isDark ? 'flex-end' : 'flex-start' }}
      type="button"
    >
      <motion.span
        layout
        transition={{
          type: 'spring',
          visualDuration: 0.8
        }}
      >
        {isDark ? <ThemeDark /> : <ThemeLight />}
      </motion.span>
    </motion.button>
  )
}
