// packages/theme/src/components/toolPanel/ToolPanel.vue
<script setup lang='ts'>
import { useSidebarControl } from '#/controller/sidebar.ts'
import { BookOpen, PanelLeftClose, PanelLeftOpen } from '#/icons'
import BackToTop from './BackToTop.vue'

const { isOpen, toggle } = useSidebarControl()
</script>

<template>
  <div class="p-1 rounded-5 right-2 top-1/2 fixed z-[--z-index-toolpanel] overflow-hidden">
    <div class="flex flex-col gap-1">
      <button
        :aria-checked="isOpen"
        class="action-button"
        role="switch"
        type="button"
        @click="toggle"
      >
        <PanelLeftOpen v-if="isOpen" />
        <PanelLeftClose v-else />
      </button>

      <button class="action-button" type="button">
        <BookOpen />
      </button>

      <BackToTop />
    </div>

    <div class="panle-background"></div>
  </div>
</template>

<style>
.action-button {
  width: 40px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 20px;
  color: var(--c-text-2);
  cursor: pointer;
  transition: color 200ms ease;

  &:hover {
    color: var(--c-brand-3);
  }
}

.panle-background {
  position: absolute;
  inset: 0;
  z-index: -1;
  background-color: var(--c-bg-navbar);
  box-shadow:
    0 2px 10px 1px hsl(0 0% 67% / 0.1),
    inset 0 0 10px 4px hsl(0 0% 80% / 0.1),
    inset 0 0 50px 4px hsl(0 0% 60% / 0.1),
    inset -1px -1px 4px hsl(0 0% 100% / 0.1);
}
</style>

// apps/docs-next/src/theme/components/ToolPanel.tsx
import { clsx } from '@repo/utils'
import { memo, useEffect } from 'react'
import { useLayout } from '../controller/layout'
import { useSidebarControl } from '../controller/sidebar'
import { useAnimation, useFPS } from '../hooks'
import { PanelLeftClose, PanelLeftOpen, Rocket } from '../icons'
import { GlassMask, ScrollIndicator } from './Effect'
import { SidebarTrigger } from './sidebar/SidebarTrigger'

export function ToolPanel() {
  const isTriggerSentinel = useLayout(state => state.isTriggerSentinel)

  return (
    <div
      className={clsx(
        'p-1 right-2 top-1/2 fixed z-[--z-index-toolpanel]',
        'opacity-0 translate-x-full transition-all duration-600 ease-out',
        'data-[show=true]:opacity-100 data-[show=true]:translate-x-0'
      )}
      data-role="toolpanel"
      data-show={isTriggerSentinel}
    >
      <div className="rounded-5 flex flex-col gap-1">
        <SidebarButton />
        <Indicator />
        <FPS />
        <BackToTop />
      </div>
      <GlassMask className="rounded-5 inset-0 absolute -z-1" />
    </div>
  )
}

const SidebarButton = memo(() => {
  const isMobile = useLayout(state => state.isMobile)
  const isTriggerSentinel = useLayout(state => state.isTriggerSentinel)
  const { isOpen, close } = useSidebarControl()

  useEffect(() => {
    if (!isTriggerSentinel) {
      close()
    }
  }, [isTriggerSentinel])

  if (!isMobile) {
    return null
  }

  return (
    <SidebarTrigger
      className={clsx(
        'text-5 text-muted-foreground flex size-10 cursor-pointer flex-center',
        'transition-color duration-200 hover:text-brand-2'
      )}
      title="侧边导航"
    >
      {isOpen ? <PanelLeftOpen /> : <PanelLeftClose />}
    </SidebarTrigger>
  )
})

const Indicator = memo(() => {
  return (
    <div className="text-6 text-teal flex size-10 flex-center">
      <ScrollIndicator />
    </div>
  )
})

const FPS = memo(() => {
  const fps = useFPS()
  return (
    <div className="text-teal flex-col size-10 items-center justify-between">
      <span className="text-3 leading-[1]">fps</span>
      <span className="text-14px leading-6">{fps}</span>
    </div>
  )
})

function BackToTop() {
  const [animation, scope] = useAnimation<HTMLButtonElement>(
    [{ transform: 'translateY(10px)' }, { transform: 'translateY(-100px)' }],
    {
      duration: 1000,
      easing: 'cubic-bezier(0.6, -0.28, 0.74, 0.05)'
    }
  )

  function backToTop() {
    animation.play()
    document.documentElement.scrollIntoView()
  }

  return (
    <button
      aria-label="back to top"
      className="text-6 text-muted-foreground flex size-10 cursor-pointer flex-center hover:text-brand-3"
      onClick={backToTop}
      ref={scope}
      title="回到顶部"
      type="button"
    >
      <Rocket />
    </button>
  )
}
