// packages/theme/src/components/ToolPanel.vue
<script setup lang='ts'>
import { shallowRef, watch } from 'vue'
import DocOutline from '#/components/doc/DocOutline.tsx'
import { Popover } from '#/components/popover'
import { useLayoutCtx } from '#/controller/layout.ts'
import { useSidebarControl } from '#/controller/sidebar.ts'
import { useFPS } from '#/hooks'
import { BookOpen, PanelLeftClose, PanelLeftOpen } from '#/icons'
import BackToTop from './BackToTop.vue'
import { GlassMask, ScrollIndicator } from './Effect.tsx'
import SidebarTrigger from './sidebar/SidebarTrigger.vue'

const { isMobile, isTriggerSentinel } = useLayoutCtx()

const { isOpen: sidebarOpened, close: closeSidebar } = useSidebarControl()

const outlineOpened = shallowRef(false)

watch(isMobile, () => (outlineOpened.value = false))

watch(
  () => isTriggerSentinel.value,
  value => {
    if (value === false) {
      outlineOpened.value = false
      closeSidebar()
    }
  }
)

function onOutlineClick(event: MouseEvent) {
  const target = event.target as HTMLElement
  if (target.tagName === 'A' || target.classList.contains('outline-item')) {
    outlineOpened.value = false
  }
}

const { fps } = useFPS()
</script>

<template>
  <div
    :class="[
      'p-1 top-1/2 right-2 fixed z-[--z-index-toolpanel]',
      'opacity-0 translate-x-full transition-all duration-600 ease-out',
      'data-[show=true]:opacity-100 data-[show=true]:translate-x-0'
    ]"
    data-role="toolpanel"
    :data-show="isTriggerSentinel"
  >
    <div class="rounded-5 flex flex-col gap-1">
      <SidebarTrigger
        v-if="isMobile"
        class="tool-button"
        title="侧边导航"
      >
        <PanelLeftOpen v-if="sidebarOpened" />
        <PanelLeftClose v-else />
      </SidebarTrigger>

      <Popover
        v-if="isMobile"
        v-model:open="outlineOpened"
        :delay-open-frame="2"
        :keep-alive="true"
        :mask-closable="false"
        :offset="20"
        placement="left"
        fixed
      >
        <template #trigger>
          <button
            :aria-checked="outlineOpened"
            aria-label="outline-button"
            class="tool-button"
            role="switch"
            title="本地导航"
            type="button"
          >
            <BookOpen />
          </button>
        </template>

        <div
          class="p-4 min-w-60 relative isolate"
          @click="onOutlineClick"
        >
          <DocOutline />
          <GlassMask class="rounded-4 inset-0 absolute -z-1" />
        </div>
      </Popover>

      <div class="text-6 text-teal flex size-10 flex-center">
        <ScrollIndicator />
      </div>

      <div class="text-teal flex-col size-10 items-center justify-between">
        <span class="text-3 leading-[1]">fps</span>
        <span class="text-14px leading-6">{{ fps }}</span>
      </div>

      <BackToTop />
    </div>
    <GlassMask class="rounded-5 inset-0 absolute -z-1" />
  </div>
</template>

// apps/docs-next/src/theme/components/ToolPanel.tsx
import { clsx } from '@repo/utils'
import { memo, useEffect } from 'react'
import { useLayout } from '../controller/layout'
import { useSidebarControl } from '../controller/sidebar'
import { useAnimation, useFPS } from '../hooks'
import { PanelLeftClose, PanelLeftOpen, Rocket } from '../icons'
import { GlassMask, ScrollIndicator } from './Effect'
import { SidebarTrigger } from './sidebar/SidebarTrigger'

export function ToolPanel() {
  const isTriggerSentinel = useLayout(state => state.isTriggerSentinel)

  return (
    <div
      className={clsx(
        'p-1 right-2 top-1/2 fixed z-[--z-index-toolpanel]',
        'opacity-0 translate-x-full transition-all duration-600 ease-out',
        'data-[show=true]:opacity-100 data-[show=true]:translate-x-0'
      )}
      data-role="toolpanel"
      data-show={isTriggerSentinel}
    >
      <div className="rounded-5 flex flex-col gap-1">
        <SidebarButton />
        <Indicator />
        <FPS />
        <BackToTop />
      </div>
      <GlassMask className="rounded-5 inset-0 absolute -z-1" />
    </div>
  )
}

const SidebarButton = memo(() => {
  const isMobile = useLayout(state => state.isMobile)
  const isTriggerSentinel = useLayout(state => state.isTriggerSentinel)
  const { isOpen, close } = useSidebarControl()

  useEffect(() => {
    if (!isTriggerSentinel) {
      close()
    }
  }, [isTriggerSentinel])

  if (!isMobile) {
    return null
  }

  return (
    <SidebarTrigger className="tool-button" title="侧边导航">
      {isOpen ? <PanelLeftOpen /> : <PanelLeftClose />}
    </SidebarTrigger>
  )
})

const Indicator = memo(() => {
  return (
    <div className="text-6 text-teal flex size-10 flex-center">
      <ScrollIndicator />
    </div>
  )
})

const FPS = memo(() => {
  const fps = useFPS()
  return (
    <div className="text-teal flex-col size-10 items-center justify-between">
      <span className="text-3 leading-[1]">fps</span>
      <span className="text-14px leading-6">{fps}</span>
    </div>
  )
})

function BackToTop() {
  const [animation, scope] = useAnimation<HTMLButtonElement>(
    [{ transform: 'translateY(10px)' }, { transform: 'translateY(-100px)' }],
    {
      duration: 1000,
      easing: 'cubic-bezier(0.6, -0.28, 0.74, 0.05)'
    }
  )

  function backToTop() {
    animation.play()
    document.documentElement.scrollIntoView()
  }

  return (
    <button
      aria-label="back to top"
      className="text-6 text-muted-foreground flex size-10 cursor-pointer flex-center hover:text-brand-3"
      onClick={backToTop}
      ref={scope}
      title="回到顶部"
      type="button"
    >
      <Rocket />
    </button>
  )
}
