// packages/theme/src/components/ViewportSentinel.vue
<script setup lang="ts">
import { computed, onMounted, useTemplateRef } from 'vue'
import { useIntersectionObserver } from '#/hooks'

const props = defineProps<{
  top?: number
  bottom?: number
}>()

const emit = defineEmits<{
  visibleChange: [visible: boolean]
}>()

const style = computed(() => {
  if (props.top) {
    return { top: props.top + 'px' }
  }
  if (props.bottom) {
    return { bottom: props.bottom + 'px' }
  }
  return undefined
})

const sentinel = useTemplateRef('sentinel')

const { observe } = useIntersectionObserver()

onMounted(() => {
  observe(sentinel.value, entry => {
    emit('visibleChange', entry.isIntersecting)
  })
})
</script>

<template>
  <div
    ref="sentinel"
    aria-hidden="true"
    class="h-1 inset-x-0 absolute -z-1"
    data-role="sentinel"
    :style="style"
  ></div>
</template>

// apps/docs-next/src/theme/components/ViewportSentinel.tsx
import type { CSSProperties } from 'react'
import { useEffect, useRef } from 'react'
import { useIntersectionObserver } from '../hooks'

interface Props {
  top?: number
  bottom?: number
  onVisibleChange?: (visible: boolean) => void
}

export function ViewportSentinel(props: Props) {
  const { top, bottom, onVisibleChange } = props

  const sentinel = useRef<HTMLDivElement | null>(null)
  const { observe } = useIntersectionObserver()

  useEffect(() => {
    observe(sentinel.current, entry => {
      onVisibleChange?.(entry.isIntersecting)
    })
  }, [])

  const style: CSSProperties = {}
  if (top) {
    style.top = top + 'px'
  } else if (bottom) {
    style.bottom = bottom + 'px'
  }

  return (
    <div
      aria-hidden="true"
      className="absolute inset-x-0 -z-1 h-1"
      data-role="sentinel"
      ref={sentinel}
      style={style}
    ></div>
  )
}
