// packages/theme/src/components/ViewportSentinel.tsx
import { computed, defineComponent, onMounted, useTemplateRef } from 'vue'
import { useIntersectionObserver } from '#/hooks'

export const ViewportSentinel = defineComponent<
  { top?: number; bottom?: number },
  { visibleChange: (value: boolean) => void }
>(
  (props, { emit }) => {
    const style = computed(() => {
      const { top, bottom } = props
      if (top) {
        return { top: top + 'px' }
      }
      if (bottom) {
        return { bottom: bottom + 'px' }
      }
      return undefined
    })

    const sentinel = useTemplateRef<HTMLDivElement>('sentinel')

    const { observe } = useIntersectionObserver()

    onMounted(() => {
      observe(sentinel.value, entry => {
        emit('visibleChange', entry.isIntersecting)
      })
    })

    return () => (
      <div
        aria-hidden="true"
        class="absolute inset-x-0 -z-1 h-1"
        data-role="sentinel"
        ref="sentinel"
        style={style.value}
      ></div>
    )
  },
  { name: 'ViewportSentinel', props: ['top'] }
)

// apps/docs-next/src/theme/components/ViewportSentinel.tsx
import type { CSSProperties } from 'react'
import { useEffect, useRef } from 'react'
import { useIntersectionObserver } from '../hooks'

interface Props {
  top?: number
  bottom?: number
  onVisibleChange?: (visible: boolean) => void
}

export function ViewportSentinel(props: Props) {
  const { top, bottom, onVisibleChange } = props

  const sentinel = useRef<HTMLDivElement | null>(null)
  const { observe } = useIntersectionObserver()

  useEffect(() => {
    observe(sentinel.current, entry => {
      onVisibleChange?.(entry.isIntersecting)
    })
  }, [])

  const style: CSSProperties = {}
  if (top) {
    style.top = top + 'px'
  } else if (bottom) {
    style.bottom = bottom + 'px'
  }

  return (
    <div
      aria-hidden="true"
      className="absolute inset-x-0 -z-1 h-1"
      data-role="sentinel"
      ref={sentinel}
      style={style}
    ></div>
  )
}
