// apps/docs-next/src/theme/components/sidebar/SidebarTrigger.tsx
import type { PropsWithChildren } from 'react'
import type { WithHTMLProps } from '../../types'
import { clsx } from '@repo/utils'
import { useSidebarControl } from '../../controller/sidebar'

export function SidebarTrigger(
  props: PropsWithChildren<WithHTMLProps<HTMLButtonElement>>
) {
  const { className, children } = props
  const { isOpen, toggle } = useSidebarControl()

  return (
    <button
      aria-checked={isOpen}
      aria-label="sidebar-button"
      className={clsx('flex cursor-pointer flex-center', className)}
      onClick={toggle}
      role="switch"
      type="button"
    >
      {children}
    </button>
  )
}

// packages/ui/src/components/widgets/SidebarTrigger.vue
<script setup lang='ts'>
import { useSidebarControl } from '#/controller/sidebar.ts'
import Menu from '../icons/Menu.vue'

const { open } = useSidebarControl()
</script>

<template>
  <button
    aria-label="sidebar-button"
    class="flex-center text-6 px-4 flex cursor-pointer"
    type="button"
    @click="open"
  >
    <Menu />
  </button>
</template>
