// packages/theme/src/components/doc/DocContent.vue
<script setup lang='ts'>
import type { Page } from '#/types'
import { watch } from 'vue'
import { setPageData } from '#/controller/layout'
import NotFound from '../NotFound.tsx'
import DocFooter from './DocFooter.vue'
import DocOutline from './DocOutline.tsx'

const props = defineProps<{ page?: Page }>()

watch(
  () => props.page,
  value => setPageData(value ?? null),
  { immediate: true }
)
</script>

<template>
  <div v-if="page" class="flex" data-role="doc-content">
    <div class="px-8 pb-24 flex-1 min-w-0">
      <article id="content" class="ebb-doc">
        <slot></slot>
      </article>
      <DocFooter />
    </div>

    <div class="pl-4 w-64" data-role="doc-aside">
      <aside class="pb-12 pt-[calc(var(--h-navbar)+48px)] flex-col w-56 inset-y-0 fixed">
        <div
          :class="[
            'flex-col flex-1 overflow-x-hidden overflow-y-auto',
            'opacity-60 transition-opacity hover:opacity-100'
          ]"
        >
          <DocOutline />
          <div class="flex-1"></div>
        </div>
      </aside>
    </div>
  </div>
  <NotFound v-else />
</template>

// apps/docs-next/src/theme/components/doc/DocContent.tsx
'use client'
import type { PropsWithChildren } from 'react'
import type { Page } from '../../types'
import { clsx } from '@repo/utils'
import { useEffect } from 'react'
import { pageStore } from '../../controller/layout'
import { DocFooter } from './DocFooter'
import { DocOutline } from './DocOutline'

interface Props {
  page: Page
}

export function DocContent(props: PropsWithChildren<Props>) {
  const { page, children } = props

  useEffect(() => {
    pageStore.setState(page)
  }, [page])

  return (
    <div className="flex" data-role="doc-content">
      <div className="min-w-0 flex-1 px-8 pb-24">
        <article className="ebb-doc" id="content">
          {children}
        </article>
        <DocFooter />
      </div>

      <div className="w-64 pl-4" data-role="doc-aside">
        <aside className="fixed inset-y-0 w-56 flex-col pt-[calc(var(--h-navbar)+48px)] pb-12">
          <div
            className={clsx(
              'flex-1 flex-col overflow-y-auto overflow-x-hidden',
              'opacity-60 transition-opacity hover:opacity-100'
            )}
          >
            <DocOutline />
            <div className="flex-1"></div>
          </div>
        </aside>
      </div>
    </div>
  )
}
